include:
  - project: operations/gitlab-hooks/gitlab-pipeline-templates
    file: golang.yaml
  - project: operations/gitlab-hooks/gitlab-pipeline-templates
    file: build-and-push-docker-image.yaml
  - project: operations/gitlab-hooks/gitlab-pipeline-templates
    file: dockerfile-lint.yaml

stages:
  - test
  - publish

test:
  stage: test
  extends: .golang
  script:
    - make lint

build-image:
  variables:
    DOCKER_IMAGE_TAG: repo.bison-group.com:5010/bison-operations/policy-report-publisher:develop-latest
    DOCKER_BUILD_ARGS: --build-arg VERSION=develop-latest --build-arg BUILD=${CURRENT_BUILD_TIME}
  stage: publish
  extends: .build-image
  needs:
    - test
  only:
    - main

build-image-tag:
  variables:
    DOCKER_IMAGE_TAG: repo.bison-group.com:5010/bison-operations/policy-report-publisher:${CI_COMMIT_TAG}
    DOCKER_BUILD_ARGS: --build-arg VERSION=${CI_COMMIT_TAG} --build-arg BUILD=${CURRENT_BUILD_TIME}
    DOCKER_PUSH_ALWAYS: 'true'
  stage: publish
  extends: .build-image
  needs:
    - test
  only:
    - tags
  except:
    - branches
